marks = []
f1=input("Please Enter Marks here :")
marks.append(f1)
f2=input("Please Enter Marks here :")
marks.append(f2)
f3=input("Please Enter Marks here :")
marks.append(f3)
f4=input("Please Enter Marks here :")
marks.append(f4)
f5=input("Please Enter Marks here :")
marks.append(f5)
f6=input("Please Enter Marks here :")
marks.append(f6)
f7=input("Please Enter Marks here :")
marks.append(f7)
print(marks)